[package]
name = "rust_memvis"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.27", features = ["ptrace"] }
libc = "0.2"
regex = "1"
termion = "2"
prettytable-rs = "0.10"
clap = { version = "4.4", features = ["derive"] }
lazy_static = "1.4"
log = "0.4"
env_logger = "0.10"
